version: "3.8"

services:
  flask-app:
    build: .
    container_name: chatbot
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOCALHOST_IP=${LOCALHOST_IP}
    volumes:
      - .:/app
      - ./static:/app/static  # ✅ Corrected indentation
    restart: unless-stopped

  redis:
    image: redis
    container_name: redis-server
    restart: unless-stopped
    ports:
      - "6379:6379"
